#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the cutTheSticks function below.
def cutTheSticks(arr):
    n=len(arr)
    ls=[len(arr)]
    ab=arr.copy()
    while n!=0:
        m=min(ab)
        ab=[i for i in ab if i!=m]
        #print(ab)
        n=len(ab)
        if n!=0:
            ls.append(n)
    return ls
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    result = cutTheSticks(arr)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
