#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the minimumDistances function below.
def minimumDistances(a):
    res=None
    b=0
    for i in a:
        ind=[index for index,element in enumerate(a) if element==i]
        if len(ind)>1:
            b=ind[1]-ind[0]
            if res==None:
                res=b
            elif res>b:
                res=b
    if res==None:
        res=-1
    return res
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    a = list(map(int, input().rstrip().split()))

    result = minimumDistances(a)

    fptr.write(str(result) + '\n')

    fptr.close()
